version: '1.0'
metadata:
  name: mern-dev
  description: MongoDB + Express + React + Node
  author: repdev
  created_at: 2025-10-17

hooks:
  preDown:
    - echo "Backing up Mongo volume (sample)"
  postDown:
    - echo "Cleanup finished (sample)"

services:
  web:
    image: node:20
    container_name: mern_web
    working_dir: /usr/src/app
    volumes:
      - ./web:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    command: ["npm", "run", "dev"]
    depends_on:
      - api
    # Wait for API to be ready before considering web ready
    wait_for:
      type: http
      url: http://localhost:4000/health
      timeout: 60000
      interval: 2000
    hooks:
      afterStart:
        - echo "Web started (sample)"

  api:
    image: node:20
    container_name: mern_api
    working_dir: /usr/src/app
    volumes:
      - ./api:/usr/src/app
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
    command: ["npm", "run", "dev"]
    depends_on:
      - db
    # Wait for MongoDB to accept TCP connections
    wait_for:
      type: tcp
      host: 127.0.0.1
      port: 27017
      timeout: 60000
      interval: 2000
    hooks:
      afterStart:
        - echo "Run API migrations here (sample)"
        # - docker exec mern_api npm run migrate

  db:
    image: mongo:6
    container_name: mern_db
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
